# Generated by Django 4.0.6 on 2022-07-05 03:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.FileField(upload_to='')),
                ('post_created_at', models.DateTimeField(default=datetime.datetime(2022, 7, 5, 9, 27, 59, 338792))),
            ],
            options={
                'db_table': 'app_post',
            },
        ),
    ]
