# Generated by Django 4.0.6 on 2022-07-05 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apppost',
            name='post_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 9, 29, 46, 982630)),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='post_img',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
