# Generated by Django 4.0.6 on 2022-07-05 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restapi', '0002_alter_apppost_post_created_at_alter_apppost_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='apppost',
            name='post_by',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='apppost',
            name='post_desc',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='apppost',
            name='post_title',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='apppost',
            name='post_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 9, 32, 32, 224977)),
        ),
    ]
