# Generated by Django 4.0.4 on 2022-07-22 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_restapi', '0003_apppost_post_by_apppost_post_desc_apppost_post_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apppost',
            old_name='post_by',
            new_name='video_by',
        ),
        migrations.RenameField(
            model_name='apppost',
            old_name='post_desc',
            new_name='video_desc',
        ),
        migrations.RenameField(
            model_name='apppost',
            old_name='post_img',
            new_name='video_file',
        ),
        migrations.RenameField(
            model_name='apppost',
            old_name='post_title',
            new_name='video_title',
        ),
        migrations.RemoveField(
            model_name='apppost',
            name='post_created_at',
        ),
        migrations.AddField(
            model_name='apppost',
            name='video_created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 22, 11, 59, 20, 640238)),
        ),
    ]
